### ISSUE TITLE
Add Travis CI Integration

### ISSUE THREAD

**Issue by kosta** [kosta/gloomhaven-stacks#18]
Should also run tests if #17 is done, but checking whether webpack works is already something.

**Comment by signed** [comment]
added travis configuration: https://github.com/kosta/gloomhaven-stacks/pull/21

builds: https://travis-ci.org/signed/gloomhaven-stacks/builds

**Comment by kosta** [comment]
Wow! Thank you for doing this! I'm adding the integration as I type this.

**Comment by kosta** [comment]
https://travis-ci.com/kosta/gloomhaven-stacks 

# 🥇

**Comment by kosta** [comment]
Thank you for doing this! It made me add https://travis-ci.com/kosta/atomic-counter 😁

**Comment by signed** [comment]
setting up travis is really straight forward. Makes me wonder why setting up Jenkins is that hard :)

**Comment by kosta** [comment]
Don't get me started on Jenkins ;)
